### ISSUE TITLE
NoSuchMethodError from ViewFinderHelper.buildViewFinder

### ISSUE THREAD

**Issue by JessHolle** [joerogers/EspressoDescendantActions#2]
I am getting:

java.lang.NoSuchMethodError: No static method create(Ljavax/inject/Provider;Ljavax/inject/Provider;)Landroid/support/test/espresso/core/internal/deps/dagger/internal/Factory; in class Landroid/support/test/espresso/base/ViewFinderImpl_Factory; or its super classes (declaration of 'android.support.test.espresso.base.ViewFinderImpl_Factory' appears in /data/app/...)
at com.forkingcode.espresso.contrib.ViewFinderHelper.buildViewFinder(ViewFinderHelper.java:18)

for all my usages of DescendantViewAction.  I see a comment in the code saying "Some risk since using Dagger generated factory directly" here, but it is unclear how to fix this.

**Comment by JessHolle** [comment]
A little disassembly suggests this would be fixed by building against Espresso 3.0.2 rather than 3.0.0.

**Comment by joerogers** [comment]
I check periodically to see if they did a release and 3.0.2 still indicates its in beta at https://developer.android.com/training/testing/release-notes. Looks like they updated the test instructions but not the release notes. I'll rebuild and deploy to jCenter later today.

**Comment by JessHolle** [comment]
Hmm...  I did not realize 3.0.2 was in beta -- as I update when Android Studio highlights something in build.gradle as no longer being the latest available version.

**Comment by JessHolle** [comment]
According to https://mvnrepository.com/artifact/com.android.support.test.espresso/espresso-core 3.0.2 is not a beta.

**Comment by joerogers** [comment]
Its not in beta. They didn't update the release notes however.

**Comment by JessHolle** [comment]
Thanks!
